### ISSUE TITLE
文章目录索引是怎么弄的

### ISSUE THREAD

**Issue by tyrionyu** [blanboom/blanboom.github.io#1]
Hexo 主题 Landscape 改造小记   这个文章目录索引是怎么弄的。

**Comment by blanboom** [comment]
手动在 Markdown 文件中添加 HTML 的…… https://raw.githubusercontent.com/blanboom/Blanboom-Blog/master/source/_posts/2015-02-07-hack-hexo-theme-landscape.md

**Comment by tyrionyu** [comment]
好的，谢谢，我试试。
